export const BONE_PICK_RADIUS_PX = 12;
export const PICK_DRAG_THRESHOLD_PX = 4;
export const SELECTION_HIGHLIGHT_COLOR = 0xe4e4e7;
export const SELECTION_BOX_PADDING = 1.04;
export const BONE_SELECTION_SPHERE_RADIUS = 0.05;
