/** Display ids for keyboard key icons / per-key labels in chord UI. */
export type KeyboardKeyId
  = | 'command'
    | 'ctrl'
    | 'shift'
    | 'space'
    | '1'
    | '2'
    | '3'
    | 'q'
    | 'w'
    | 'e'
    | 'r'
    | 'b'
    | 's'
    | 'n'
    | 'c'
    | 'v'
    | 'z'
    | 'y'
    | 'arrow_left'
    | 'arrow_right'
    | 'arrow_up'
    | 'arrow_down'
    | 'delete';
